export { softenConjunctions } from './conjunctions.js'
export { passiveToActive } from './passive.js'
export { applyContractions } from './contractions.js'
export { addTransitions } from './transitions.js'
export { adjustPacing } from './pacing.js'
export { removeRepetitivePhrases } from './repetitive.js'
export { diversifyVocabulary } from './vocabulary.js'
export { hedgeAbsoluteStatements } from './hedging.js'
export { addConjunctionStarts } from './conjunction-starts.js'
export { varySentenceOpenings } from './sentence-variety.js'
export { fabricateText } from './fabricate.js'
export { lintMarkdown, fixMarkdown } from './lint.js'
export type { LintIssue, LintResult } from './lint.js'
